// Copied from runtime/src/motionwords.ts by runtime/scripts/build.mjs. Do not edit here.
// Kit things and the words that mean them. Ported from hermes-plugin/yui/motion_hero.py (WORDS, WEAK, COOK, SKIP): keep the two in step.
export const WORDS: Record<string, string> = {
  "dog": "dogs?|pupp(?:y|ies)|canines?",
  "cat": "cats?|kittens?|kitty|felines?",
  "fish": "fish(?:es)?|salmon|trout|goldfish",
  "bird": "birds?|sparrows?|robins?|parrots?|owls?|eagles?|pigeons?|songbirds?",
  "chicken": "chickens?|hens?|roosters?|poultry",
  "cow": "cows?|cattle|cows'|dairy|bulls?",
  "turtle": "turtles?|tortoises?",
  "bee": "bees?|beehives?|bumblebees?",
  "butterfly": "butterfl(?:y|ies)|caterpillars?|moths?",
  "heart": "hearts?|cardiac|heartbeats?",
  "lungs": "lungs?|breathing|respiratory",
  "brain": "brains?|neurons?|neural",
  "stomach": "stomachs?|digestion|digestive",
  "tooth": "teeth|tooth|dental|dentist",
  "bone": "bones?|skeleton|skeletal",
  "eyeball": "eyes?|eyeballs?|retina",
  "car": "cars?|automobiles?|sedans?|vehicles?",
  "bus": "buses|bus|buses",
  "truck": "trucks?|lorry|lorries|freight",
  "plane": "planes?|airplanes?|aeroplanes?|aircraft|jets?|airliners?|flights?",
  "boat": "boats?|sailboats?|sailing|yachts?|ferr(?:y|ies)",
  "bicycle": "bicycles?|bikes?|cycling|cyclists?",
  "train": "trains?|locomotives?|railways?|railroads?",
  "rocket": "rockets?|spacecraft|spaceships?|space shuttle",
  "hammer": "hammers?|mallets?",
  "wrench": "wrenches|wrench|spanners?",
  "scissors": "scissors|shears",
  "saw": "saws?|sawing|handsaws?",
  "screwdriver": "screwdrivers?",
  "paintbrush": "paint ?brush(?:es)?|paint(?:ing)? a (?:wall|room|house)",
  "key": "keyholes?|keychains?|(?:door|house|car|front|room) keys?",
  "ladder": "ladders?",
  "house": "houses?|homes?(?! (?:screen|page|tab|button|row|view|feed))|apartments?|cottages?|mortgages?|rent(?:ing)?|landlords?",
  "castle": "castles?|fortress(?:es)?|fortif\\w+|medieval",
  "skyscraper": "skyscrapers?|high-?rises?|office buildings?",
  "city": "cit(?:y|ies)|skylines?|downtown",
  "colosseum": "colosseum|coliseum|roman empire|romans?|rome|gladiators?",
  "church": "churche?s?|cathedrals?|chapels?",
  "tent": "tents?|camping|campsites?|campers?",
  "bridge": "bridges?|suspension bridges?",
  "lighthouse": "lighthouses?",
  "mug": "mugs?|cups? of|coffee|tea cups?|teacups?|espresso|latte",
  "lemon": "lemons?|citrus",
  "apple": "apples?",
  "pizza": "pizzas?",
  "bread": "bread|loaf|loaves|baguettes?|sourdough",
  "egg": "eggs?",
  "cake": "cakes?|birthdays?|cupcakes?",
  "bottle": "bottles?|wine|beer|brew(?:ing)?",
  "chair": "chairs?|seating",
  "bed": "beds?|sleep(?:ing)?|bedroom|mattress",
  "clock": "clocks?|timers?|o'clock",
  "book": "books?|novels?|libraries|library",
  "laptop": "laptops?|notebooks? computers?",
  "camera": "cameras?|photograph(?:y|s)?|photos?",
  "umbrella": "umbrellas?|rain(?:y|ing)? gear",
  "battery": "batter(?:y|ies)|chargers?",
  "plant": "plants?|houseplants?|seedlings?|sprouts?|garden(?:ing)?|flowerpots?|photosynthesis",
  "coins": "coins?|money|cash|savings?|dollars?|piggy bank",
  "box": "boxes|box|parcels?|packages?|cartons?|shipping boxes?|deliver(?:y|ies)",
  "can": "watering cans?",
  "tank": "tanks?|reservoirs?|water levels?",
  "robot": "robots?|androids?",
  "engine": "engines?|pistons?|motors?|combustion|four-?stroke",
  "newsletter": "newsletters?|magazines?|newspapers?",
  "envelope": "envelopes?|e-?mails?|letters?|inbox|mail",
  "calendar": "calendars?|schedules?|deadlines?|appointments?",
  "globe": "globes?|continents?|planets?|the earth|the world|world map|countries"
};
export const WEAK = new Set(["apple", "bed", "book", "bottle", "box", "calendar", "camera", "city", "clock", "coins", "egg", "envelope", "globe", "house", "key", "lemon", "mug"]);
export const COOK = /\b(roast(?:ed|ing)?|bak(?:e|ed|ing)|cook(?:ed|ing)?|recipe|oven|dinner|grill(?:ed|ing)?|fry|fried|garlic|stuff(?:ed|ing)?|carv(?:e|ing))\b/i;
export const SKIP = /\bapi\.three\b|\b3d\b|three\.js|\breal 3d\b/i;
