#!/usr/bin/env python3
"""Copy the Yui channel guide into the plugin, and optionally publish it.

Source of truth: yuigui/spec/CHANNEL.md. The part agents see starts at
"## You are talking to someone in Yui" and runs to the end. It is copied
verbatim; this script never edits the text.

    sync_channel.py              # write yui/CHANNEL.md (bundled with the plugin)
    sync_channel.py --check      # exit 1 if the bundled copy is stale
    sync_channel.py --publish    # also upsert it into PROOF yui_channel_guides,
                                 # which yui-connect hands to non-Hermes agents

The version string is the spec title's version plus the first 8 hex of the
text's SHA-256, e.g. "v0+3f2a9c1e", so any edit shows up as a new version.
"""
import argparse, base64, hashlib, json, os, re, subprocess, sys, urllib.request
from pathlib import Path

HERE = Path(__file__).resolve().parent
SPEC = Path(os.environ.get("YUI_CHANNEL_SPEC", Path.home() / "dev/yuigui/spec/CHANNEL.md"))
BUNDLED = HERE / "yui" / "CHANNEL.md"
START = "## You are talking to someone in Yui"
REF = "ewzzaoperdpxqxkshynx"


def extract(spec: str) -> tuple[str, str]:
    title = spec.splitlines()[0]
    m = re.search(r"\bv(\d+(?:\.\d+)*)\b", title)
    if not m:
        sys.exit(f"no version in the title: {title!r}")
    i = spec.find(START)
    if i < 0:
        sys.exit(f"{SPEC} has no {START!r} section")
    body = spec[i:].rstrip() + "\n"
    version = f"v{m.group(1)}+{hashlib.sha256(body.encode()).hexdigest()[:8]}"
    return version, body


def render(version: str, body: str) -> str:
    # Line 1 carries the version; the adapter strips it off and prints it above the text.
    return f"<!-- yui-channel-guide {version} (generated by sync_channel.py from yuigui/spec/CHANNEL.md; do not edit) -->\n{body}"


def publish(version: str, body: str) -> None:
    raw = subprocess.check_output(["security", "find-generic-password", "-s", "Supabase CLI", "-w"]).decode().strip()
    token = os.environ.get("SUPABASE_ACCESS_TOKEN") or base64.b64decode(raw.removeprefix("go-keyring-base64:")).decode()
    q = ("insert into public.yui_channel_guides(version, body) values ($v$" + version + "$v$, $b$" + body + "$b$) "
         "on conflict (version) do nothing")
    if "$b$" in body or "$v$" in version:
        sys.exit("guide text contains a dollar-quote tag")
    req = urllib.request.Request(f"https://api.supabase.com/v1/projects/{REF}/database/query", method="POST",
                                 data=json.dumps({"query": q}).encode(),
                                 headers={"authorization": f"Bearer {token}", "content-type": "application/json",
                                          "user-agent": "yui-sync-channel"})
    with urllib.request.urlopen(req, timeout=30) as r:
        r.read()
    print(f"published {version} to yui_channel_guides")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--publish", action="store_true")
    a = ap.parse_args()
    version, body = extract(SPEC.read_text())
    out = render(version, body)
    if a.check:
        ok = BUNDLED.exists() and BUNDLED.read_text() == out
        print(f"{'up to date' if ok else 'STALE'}: {version}")
        return 0 if ok else 1
    BUNDLED.write_text(out)
    print(f"wrote {BUNDLED} ({version}, {len(body)} chars)")
    if a.publish:
        publish(version, body)
    return 0


if __name__ == "__main__":
    sys.exit(main())
