#!/usr/bin/env node
// Builds what the native runtime ships (NATIVE-1):
//   1. src/crew.gen.ts from profiles/<name>/ (profile.json, soul.md, first.yui);
//   2. supabase/functions/_native/: the runtime's src plus the model bridge's
//      client, copied for the yui-native edge function (Deno bundles only what
//      is under supabase/functions).
// node runtime/scripts/build.mjs          write both
// node runtime/scripts/build.mjs --check  exit 1 when either is stale
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const runtime = join(here, "..");
const repo = join(runtime, "..");
const check = process.argv.includes("--check");
const stale = [];

function put(path, text) {
  const old = existsSync(path) ? readFileSync(path, "utf8") : null;
  if (old === text) return;
  if (check) stale.push(path.slice(repo.length + 1));
  else {
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, text);
    console.log(`wrote ${path.slice(repo.length + 1)}`);
  }
}

// 1. The crew, baked in. Each folder goes through the runtime's own loader,
// so a profile that fails its check never ships.
const { loadProfile } = await import("../src/profiles.ts");
const crew = {};
const bad = [];
const dir = join(runtime, "profiles");
for (const base of readdirSync(dir, { withFileTypes: true }).filter((d) => d.isDirectory()).map((d) => d.name).sort()) {
  const read = (n) => (existsSync(join(dir, base, n)) ? readFileSync(join(dir, base, n), "utf8") : null);
  try {
    crew[base] = loadProfile(base, read);
  } catch (e) {
    bad.push(e.message);
  }
}
if (bad.length) {
  console.error(`profiles that fail their check:\n  ${bad.join("\n  ")}`);
  process.exit(1);
}
put(join(runtime, "src", "crew.gen.ts"),
  "// Generated by runtime/scripts/build.mjs from runtime/profiles/. Do not edit.\n"
  + 'import type { Profile } from "./types.ts";\n\n'
  + `export const CREW: Record<string, Profile> = ${JSON.stringify(crew, null, 2)};\n`);

// 2. The edge copy.
const edge = join(repo, "supabase", "functions", "_native");
const head = (from) => `// Copied from ${from} by runtime/scripts/build.mjs. Do not edit here.\n`;
const shims = new Set(["openai.ts", "sse.ts", "thread.ts", "fences.ts"]); // re-exports of the model bridge
for (const f of readdirSync(join(runtime, "src")).filter((f) => f.endsWith(".ts")).sort()) {
  if (shims.has(f)) continue;
  put(join(edge, f), head(`runtime/src/${f}`) + readFileSync(join(runtime, "src", f), "utf8"));
}
for (const f of shims) {
  put(join(edge, f), head(`adapters/openai-compat/src/${f}`) + readFileSync(join(repo, "adapters", "openai-compat", "src", f), "utf8"));
}

if (check && stale.length) {
  console.error(`stale, run node runtime/scripts/build.mjs:\n  ${stale.join("\n  ")}`);
  process.exit(1);
}
if (check) console.log("runtime build is current");
